# Generated by Django 4.2.5 on 2023-10-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="studentNum",
            field=models.IntegerField(max_length=15),
        ),
    ]
