# Generated by Django 4.2.5 on 2023-10-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_userinfo_studentnum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="studentNum",
            field=models.BigIntegerField(max_length=15),
        ),
    ]
