# Generated by Django 4.2.5 on 2023-10-15 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_userinfo_studentnum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="end_time",
            new_name="clocking_in_time",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="start_time",
        ),
    ]
