# Generated by Django 4.1 on 2023-10-16 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_end_time_userinfo_clocking_in_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="user_type",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.usertype",
            ),
        ),
    ]
